stages:
  - build    # 线上代码打包

前端代码打包:
  stage: build
  tags:
    - micro-node
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - build
    policy: push
  before_script:
    - PROJECT_DEPS_DIR=~/${CI_PROJECT_PATH//\//_}_deps
    - echo $PROJECT_DEPS_DIR
    - mkdir -p $PROJECT_DEPS_DIR
    - ln -sf $(pwd)/package*.json $PROJECT_DEPS_DIR/
    - npm install --registry=http://npm.zhinanzhen.ai --prefix=$PROJECT_DEPS_DIR
    - NODE_PATH=$PROJECT_DEPS_DIR/node_modules
    - ln -sf $NODE_PATH node_modules
  after_script:
    - unset NODE_PATH PROJECT_DEPS_DIR
  script:
    - npm run build -- --color
    - NAME=ifchange-test
    - MASTER_NAME=static-object
    - DATE_STAMP=${CI_COMMIT_REF_NAME#*/}
    - BRANCH_NAME=${NAME}-${DATE_STAMP}
    - DEV_PATH=/opt/micro_static/${MASTER_NAME}/${NAME}
    - DEPLOY=/opt/micro_service_static/frontend-${MASTER_NAME}/${BRANCH_NAME}
    - ssh rsync_user@192.168.20.80 "rm -rf ${DEV_PATH} ${DEPLOY};mkdir -p ${DEV_PATH} ${DEPLOY};"
    - rsync -az ./build/* rsync_user@192.168.20.80:${DEV_PATH}
    - rsync -az ./build/* rsync_user@192.168.20.80:${DEPLOY}
    - echo "提测镜像地址:"项目:frontend-${MASTER_NAME} 分支:${BRANCH_NAME}
  only:  # 上线分支自动打包，master自动打包
    - /^(release|hotfix)\/.+$/
    - master
